# Generated by Django 3.2.9 on 2021-12-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Sinopsis')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Document PDF')),
                ('slug', models.SlugField(default='', editable=False, max_length=200)),
            ],
            options={
                'verbose_name': 'Magazine',
                'verbose_name_plural': 'Magazines',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Name')),
                ('short_intro1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descriere scurta 1')),
                ('short_intro2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descriere scurta 2')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Sinopsis')),
                ('profile_image', models.ImageField(blank=True, default='images/default.png', null=True, upload_to='images/', verbose_name='Profile Image')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
