# Generated by Django 3.2.9 on 2021-12-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Google Drive Link'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=200, null=True),
        ),
    ]
