# Generated by Django 3.2.9 on 2021-12-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0002_auto_20211206_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Număr Revistă'),
        ),
        migrations.AddField(
            model_name='magazine',
            name='publish_year',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Anul publicării'),
        ),
    ]
