# Generated by Django 3.2.9 on 2022-01-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0004_auto_20220107_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='featured',
            field=models.BooleanField(default=False, max_length=200, null=True, verbose_name='Prima Pagina'),
        ),
    ]
