# Generated by Django 3.2.9 on 2022-01-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0005_alter_magazine_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='featured',
            field=models.BooleanField(default=False, max_length=200, verbose_name='Prima Pagina'),
        ),
    ]
