# Generated by Django 3.2.9 on 2022-01-07 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0006_alter_magazine_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='magazine',
            options={'ordering': ('publish_year',), 'verbose_name': 'Magazine', 'verbose_name_plural': 'Magazines'},
        ),
    ]
